# golangci-lint configuration for Pocket
# https://golangci-lint.run/usage/configuration/

version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    # Default linters
    - errcheck
    - staticcheck  # Now includes gosimple
    - govet
    - ineffassign
    - unused
    # Additional linters
    - gocyclo
    - gosec
    - unconvert
    - goconst
    - gocritic
    - prealloc
    - misspell
    - unparam
    - nakedret
    - bodyclose
    - nilerr
    - godot
  
  settings:
    gocyclo:
      min-complexity: 15
    goconst:
      min-len: 3
      min-occurrences: 3
    gocritic:
      enabled-tags:
        - diagnostic
        - performance
        - style
    nakedret:
      max-func-lines: 30
    godot:
      scope: declarations
      capital: true
  
  exclusions:
    generated: lax
    rules:
      # Exclude some linters from running on test files
      - path: _test\.go
        linters:
          - gosec
          - errcheck
          - gocyclo
      
      # Exclude examples directory
      - path: examples/
        linters:
          - gosec
          - errcheck
          - godot
          - gocyclo

issues:
  # Maximum issues count per one linter
  max-issues-per-linter: 0
  
  # Maximum count of issues with the same text
  max-same-issues: 0