# golangci-lint configuration for Pocket
# https://golangci-lint.run/usage/configuration/

version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    # Default linters
    - errcheck
    - staticcheck  # Now includes gosimple
    - govet
    - ineffassign
    - unused
    # Additional linters
    - gocyclo
    - gosec
    - unconvert
    - goconst
    - gocritic
    - prealloc
    - misspell
    - unparam
    - nakedret
    - bodyclose
    - nilerr
    - godot

linters-settings:
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 3
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
  nakedret:
    max-func-lines: 30
  godot:
    scope: declarations
    capital: true
    # Enable auto-fixing for godot
    autofix: true

formatters:
  enable:
    - gofmt
    - goimports

formatters-settings:
  goimports:
    # Set the local import prefix for proper grouping
    local-prefixes: github.com/agentstation/pocket

issues:
  # Exclude some linters from running on test files
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
        - gocyclo
    
    # Exclude examples directory
    - path: examples/
      linters:
        - gosec
        - errcheck
        - godot
        - gocyclo
  
  # Don't exclude issues about comments from golint
  exclude-use-default: false
  
  # Maximum issues count per one linter
  max-issues-per-linter: 0
  
  # Maximum count of issues with the same text
  max-same-issues: 0